## <strong>2. NumPy: Universal Functions (UFunc)</strong>

In [1]:
import numpy as np

In [6]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# [+] 함수 테스트
values = np.random.randint(1, 10, size = 5)

In [9]:
compute_reciprocals(values)

array([1.        , 0.14285714, 0.16666667, 0.33333333, 0.11111111])

#### <strong>역수 계산: Python loop vs NumPy ufuncs</strong>
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [12]:
# [+] 백만 개 크기의 난수 배열 생성: 정수, 값 범위 [1, 100)
big_array = np.random.randint(1, 100, size = 1000000)

In [14]:
big_array[:100]

array([56, 87,  9, 36, 91, 42,  9,  3, 50, 68, 20, 97,  9, 41, 25, 39, 79,
       62, 88, 43,  5, 86, 75, 48, 47, 51, 82, 41, 38, 50, 94, 33, 98, 66,
       32, 49, 11, 80, 30, 34, 44, 56, 70, 26, 10, 60, 30,  8, 50, 75, 11,
       83, 31, 12, 64, 21, 48, 47, 63,  3,  3, 12, 34, 47,  5, 17, 13, 83,
       99, 52, 57, 86, 32, 25, 16,  1, 17, 67, 48, 45, 53, 34, 75, 99, 36,
       97, 14,  9, 51, 66, 69, 11, 70, 17, 72, 22, 71, 18, 82, 77],
      dtype=int32)

In [15]:
%%timeit

# [+] Python loop를 통한 역수 계산 
compute_reciprocals(big_array)

1.74 s ± 7.39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%%timeit

# [+] NumPy ufunc을 통한 벡터화된 역수 계산
1 / big_array

2.53 ms ± 113 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### <strong>유니버설 함수들</strong>

In [20]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [21]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [23]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [24]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [25]:
"""
    UFuncs: 산술 연산
"""

# 기본 산술 연산
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [26]:
"""
    UFuncs: 절댓값 계산
"""

# [+] 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])


print("|x| =", np.abs(x))

|x| = [2 1 0 1 2]


In [27]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 5)
x

array([  0.,  25.,  50.,  75., 100.])

In [31]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 11)
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [32]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [36]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [37]:
# [+] 덧셈 연산으로 집계
aggr = np.add.reduce(x)
aggr

np.int64(10)

In [38]:
# [+] 곱셈 연산으로 집계
aggr = np.multiply.reduce(x)
aggr

np.int64(24)

In [39]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = np.add.accumulate(x)
accum

array([ 1,  3,  6, 10])

In [40]:
# [+] 곱셈 연산으로 집계
accum = np.multiply.accumulate(x)
accum

array([ 1,  2,  6, 24])

In [43]:
# 집계 함수: sum()
np.random.seed(3) #랜덤 생성 시드값 사실상 고정
arr = np.random.rand(1000000) # [+] 0~1 사이의 실수 형태의 난수 배열 생성

print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum = 500422.19897015323


In [49]:
# sum(): Python 내장함수
%timeit sum(arr)

68.6 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [50]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

435 μs ± 58.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [56]:
# [+] 그 외의 집계함수
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr, 90))
print("variance =", np.var(arr))
print("standard deviation =", np.std(arr))
print("index of maximum value =", np.argmax(arr))
print("index of minimum value =", np.argmin(arr))
print("Is there any number greater than 1? =", np.any(arr > 1))
print("Is every number greater than 0? =", np.all(arr > 0)) 

max = 0.9999996367889004
min = 1.5496004267534502e-06
mean = 0.5004221989701533
median = 0.5005659265960778
percentile = 0.9001765340710965
variance = 0.08331685347394584
standard deviation = 0.28864658922971154
index of maximum value = 339543
index of minimum value = 980213
Is there any number greater than 1? = False
Is every number greater than 0? = True


In [57]:
"""다차원 집계"""

# 2차원 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [59]:
# [+] 행 방향으로 집계 (row sum)
print("Row Sum =", np.sum(arr, axis=0))

Row Sum = [14 13 13 14]


In [60]:
# [+] 열 방향으로 집계 (column sum)
print("Column Sum =", np.sum(arr, axis=1))

Column Sum = [11 24 19]
